/rm_serial_driver:
  ros__parameters:
    debug: false
    left:
      device_name: /dev/ttyACM_LEFT
      baud_rate: 115200
      hardware_flow: false
      parity: false
      stop_bits: 1
      timeout_ms: 1000
    right:
      device_name: /dev/ttyACM_RIGHT
      baud_rate: 115200
      hardware_flow: false
      parity: false
      stop_bits: 1
      timeout_ms: 1000

/armor_detector:
  ros__parameters:
    debug: false
    left:
      name: "left_camera"
      cam_info_url: "package://rm_vision_bringup/config/camera_info_left.yaml"
      exposure_time: 5500 # ms
      gain: 15.0
      invert: true
      trigger_mode: false
    right:
      name: "right_camera"
      cam_info_url: "package://rm_vision_bringup/config/camera_info_right.yaml"
      exposure_time: 5500 # ms
      gain: 15.0
      invert: true
      trigger_mode: false

    detect_color: 0
    binary_thres: 126

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    debug: false
    left:
      target_frame: gimbal_left_link_offset
    right:
      target_frame: gimbal_right_link_offset
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4.0e-4
      r_yaw: 5.0e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0