/camera_core:
  ros__parameters:
    left_camera:
      name: "left_camera"
      cam_info_url: "package://rm_vision_bringup/config/left_cam_info.yaml"
      exposure_time: 4000.0 # ms
      gain: 5.0
      invert: false
      trigger_mode: false
    right_camera:
      name: "right_camera"
      cam_info_url: "package://rm_vision_bringup/config/right_cam_info.yaml"
      exposure_time: 4000.0 # ms
      gain: 5.0
      invert: false
      trigger_mode: false

/rm_serial_driver:
  ros__parameters:
    debug: true
    left:
      device_name: /dev/ttyACM0
      baud_rate: 115200
      hardware_flow: false
      parity: false
      stop_bits: 1
      timeout_ms: 1000
    right:
      device_name: /dev/ttyACM1
      baud_rate: 115200
      hardware_flow: false
      parity: false
      stop_bits: 1
      timeout_ms: 1000

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 126

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4.0e-4
      r_yaw: 5.0e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0